### Health-check
GET http://localhost:3000/health


### Get contractByTxHash
GET http://localhost:3000/api/v1/contracts/0x886ba7003e844bfdcd98f7df9f41eb413b347b0fd81d77fefcc1c0dff7ca9d35

### Get contracts
GET http://localhost:3000/api/v1/contracts?pageSize=10&account=0xa647e98d78f56075dcc894ed273146d3be1bbe03


### Create Contract
POST http://localhost:3000/api/v1/contracts
content-type: application/json

{
  "txHash":"0x886ba7003e844bfdcd98f7df9f41eb413b347b0fd81d77fefcc1c0dff7ca9d35",
  "chainId":4,
  "account":"0xa647e98d78f56075dcc894ed273146d3be1bbe03",
  "contractAddress":"0x75b7933b3be098e39cca412de5cfbf64f22cc59b",
  "contractContent":"long long long content"
}
