# Correct .env.sample in root folder to use this file, reference: https://marketplace.visualstudio.com/items?itemName=humao.rest-client


@baseUrl = {{$dotenv EXPLORE_API_ENDPOINT}}
@accessToken = {{$dotenv EXPLORE_API_ACCESS_TOKEN}}

### Health-check
GET {{baseUrl}}/health


##### Authentication #####

### Challenge login
POST {{baseUrl}}/api/v1/authentication/challenge-login
content-type: application/json

{
  "account":"0xaa1e9d7142e09c04028f9a3bf1fe0245a6c47030"
}


### login
POST {{baseUrl}}/api/v1/authentication/login
content-type: application/json

{
  "account":"0xaa1e9d7142e09c04028f9a3bf1fe0245a6c47030",
  "signature":"0xaa1e9d7142e09c04028f9a3bf1fe0245a6c47030"
}



##### Contracts ######
### Get contractByTxHash
GET {{baseUrl}}/api/v1/contracts/0x886ba7003e844bfdcd98f7df9f41eb413b347b0fd81d77fefcc1c0dff7ca9d35


### Get all contracts with order by
GET {{baseUrl}}/api/v1/contracts?pageSize=12&order=createdAt desc&account=0xa647e98d78f56075dcc894ed273146d3be1bbe03


### Get contracts of an account
GET {{baseUrl}}/api/v1/contracts?pageSize=2&pageCursor=Co4BChYKCWNyZWF0ZWRBdBIJCLjt44DdnfYCEnBqCm5%2BY3J1c3RuZnRyYgsSGnN0YWdlLWV4cGxvcmUtYXBpLWNvbnRyYWN0IkIweDlkYTUyNjQ5YTk0ZTU1ZDhiZWQ3ZDg4NWNhZTU2NGIxNzZhOGRhMmM3Mzg3MmY2YzIzYzAxNDJjNzFlYjBlY2YMGAAgAA%3D%3D


### Create Contract Stage
POST {{baseUrl}}/api/v1/contracts
content-type: application/json

{
  "txHash":"0x886ba7003e844bfdcd98f7df9f41eb413b347b0fd81d77fefcc1c0dff7ca9d35",
  "chainId":4,
  "account":"0xa647e98d78f56075dcc894ed273146d3be1bbe03",
  "contractAddress":"0x75b7933b3be098e39cca412de5cfbf64f22cc59b",
  "contractContent":"long long long content"
}


### Create Contract Prod
POST {{baseUrl}}/api/v1/contracts
content-type: application/json

{
  "txHash":"0x2df1ce27b2a75d498baf2ce3fcb27a1d2c3e2797f49b4f683659f6ecfa300b4b",
  "chainId":56,
  "account":"0xaa1e9d7142e09c04028f9a3bf1fe0245a6c47030",
  "contractAddress":"0x0a064a4c650d9b9580c37fe8c319e22971e02e21",
  "contractContent":"long long long content"
}

##### Users ######

### Get user
GET {{baseUrl}}/api/v1/users/0xaa1e9d7142e09c04028f9a3bf1fe0245a6c47030


### Create user
POST {{baseUrl}}/api/v1/users
content-type: application/json

{
  "displayName":"Hello World",
  "account":"0xaa1e9d7142e09c04028f9a3bf1fe0245a6c47030",
  "socialUrls":["https://twitter.com/hello-world","https://fb.com/hello-world","https://instagram.com/hello-world"]
}

### Update user
PUT {{baseUrl}}/api/v1/users
Authorization: Bearer {{accessToken}}
content-type: application/json

{
  "displayName":"Hello World - 16 - 19",
  "coverUrl":"https://this.is.my.cover/abc",
  "account":"0xaa1e9d7142e09c04028f9a3bf1fe0245a6c47030",
  "socialUrls":["https://twitter.com/hello-world","https://fb.com/hello-world","https://instagram.com/hello-world"]
}



##### Collections ######

### Get collection
GET {{baseUrl}}/api/v1/collections/56-0xaa1e9d7142e09c04028f9a3bf1fe0245a6c47030


### Create collection
POST {{baseUrl}}/api/v1/collections
Authorization: Bearer {{accessToken}}
content-type: application/json

{
  "description":"Hello World",
  "account":"0xaa1e9d7142e09c04028f9a3bf1fe0245a6c47030",
  "id":"56-0xaa1e9d7142e09c04028f9a3bf1fe0245a6c47030",
  "socialUrls":["https://twitter.com/hello-world","https://fb.com/hello-world","https://instagram.com/hello-world"]
}

### Update collection
PUT {{baseUrl}}/api/v1/collections
Authorization: Bearer {{accessToken}}
content-type: application/json

{
  "description":" o oko ko ok ok ok o LGD vs RNG",
  "coverUrl":"https://this.is.my.cover/abc",
  "account":"0xaa1e9d7142e09c04028f9a3bf1fe0245a6c47030",
  "id":"56-0xaa1e9d7142e09c04028f9a3bf1fe0245a6c47030",
  "socialUrls":["https://twitter.com/hello-world","https://fb.com/hello-world","https://instagram.com/hello-world"]
}
