# Correct .env.sample in root folder to use this file, reference: https://marketplace.visualstudio.com/items?itemName=humao.rest-client


@baseUrl = {{$dotenv EXPLORE_API_ENDPOINT}}
@accessToken = {{$dotenv EXPLORE_API_ACCESS_TOKEN}}

### Health-check
GET {{baseUrl}}/health


##### Authentication #####

### Challenge login
POST {{baseUrl}}/api/v1/authentication/challenge-login
content-type: application/json

{
  "account":"0xaa1e9d7142e09c04028f9a3bf1fe0245a6c47030"
}


### login
POST {{baseUrl}}/api/v1/authentication/login
content-type: application/json

{
  "account":"0xaa1e9d7142e09c04028f9a3bf1fe0245a6c47030",
  "signature":"0xaa1e9d7142e09c04028f9a3bf1fe0245a6c47030"
}



##### Contracts ######
### Get contractByTxHash
GET {{baseUrl}}/api/v1/contracts/0x886ba7003e844bfdcd98f7df9f41eb413b347b0fd81d77fefcc1c0dff7ca9d35


### Get all contracts with countOnly
GET {{baseUrl}}/api/v1/contracts?countOnly=true
Authorization: Bearer {{accessToken}}
### Get all contracts with order by
GET {{baseUrl}}/api/v1/contracts?pageSize=12&order=createdAt desc&creator=0xa228cfab80a6738522476dec11d793d6129968b2
Authorization: Bearer {{accessToken}}

### Get next contracts
GET {{baseUrl}}/api/v1/contracts?pageSize=2&pageCursor=Co4BChYKCWNyZWF0ZWRBdBIJCLjt44DdnfYCEnBqCm5%2BY3J1c3RuZnRyYgsSGnN0YWdlLWV4cGxvcmUtYXBpLWNvbnRyYWN0IkIweDlkYTUyNjQ5YTk0ZTU1ZDhiZWQ3ZDg4NWNhZTU2NGIxNzZhOGRhMmM3Mzg3MmY2YzIzYzAxNDJjNzFlYjBlY2YMGAAgAA%3D%3D
Authorization: Bearer {{accessToken}}

### Get contracts with skip param
GET {{baseUrl}}/api/v1/contracts?offset=5&pageSize=2&order=createdAt desc
Authorization: Bearer {{accessToken}}

### Get list of published contracts
GET {{baseUrl}}/api/v1/contracts/listing?offset=5&pageSize=2&order=createdAt desc

### Create Contract Stage
POST {{baseUrl}}/api/v1/contracts
content-type: application/json
Authorization: Bearer {{accessToken}}

{
  "txHash":"0x886ba7003e844bfdcd98f7df9f41eb413b347b0fd81d77fefcc1c0dff7ca9d35",
  "chainId":4,
  "contractAddress":"0x75b7933b3be098e39cca412de5cfbf64f22cc59b",
  "contractContent":"long long long content"
}


### Update Contract
PUT {{baseUrl}}/api/v1/contracts
content-type: application/json
Authorization: Bearer {{accessToken}}

{
  "txHash":"0x2df1ce27b2a75d498baf2ce3fcb27a1d2c3e2797f49b4f683659f6ecfa300b4b",
  "published": true
}

##### Users ######

### Get user
GET {{baseUrl}}/api/v1/users/0xaa1e9d7142e09c04028f9a3bf1fe0245a6c47030


### Create user
POST {{baseUrl}}/api/v1/users
content-type: application/json

{
  "displayName":"Hello World",
  "account":"0xaa1e9d7142e09c04028f9a3bf1fe0245a6c47030",
  "socialUrls":["https://twitter.com/hello-world","https://fb.com/hello-world","https://instagram.com/hello-world"]
}

### Update user
PUT {{baseUrl}}/api/v1/users
Authorization: Bearer {{accessToken}}
content-type: application/json

{
  "displayName":"Hello World - 16 - 19",
  "coverCID":"https://this.is.my.cover/abc",
  "account":"0xaa1e9d7142e09c04028f9a3bf1fe0245a6c47030",
  "socialUrls":["https://twitter.com/hello-world","https://fb.com/hello-world","https://instagram.com/hello-world"]
}



##### Collections ######

### Get collection
GET {{baseUrl}}/api/v1/collections/56-0xaa1e9d7142e09c04028f9a3bf1fe0245a6c47030


### Create collection
POST {{baseUrl}}/api/v1/collections
Authorization: Bearer {{accessToken}}
content-type: application/json

{
  "description":"Hello World",
  "account":"0xaa1e9d7142e09c04028f9a3bf1fe0245a6c47030",
  "id":"56-0xaa1e9d7142e09c04028f9a3bf1fe0245a6c47030",
  "socialUrls":["https://twitter.com/hello-world","https://fb.com/hello-world","https://instagram.com/hello-world"]
}

### Update collection
PUT {{baseUrl}}/api/v1/collections
Authorization: Bearer {{accessToken}}
content-type: application/json

{
  "description":" o oko ko ok ok ok o LGD vs RNG",
  "coverCID":"https://this.is.my.cover/abc",
  "account":"0xaa1e9d7142e09c04028f9a3bf1fe0245a6c47030",
  "id":"56-0xaa1e9d7142e09c04028f9a3bf1fe0245a6c47030",
  "socialUrls":["https://twitter.com/hello-world","https://fb.com/hello-world","https://instagram.com/hello-world"]
}

### Media

### Create media upload url
# @name generateMedia
POST {{baseUrl}}/api/v1/medias/
content-type: application/json
Authorization: Bearer {{accessToken}}

{
  "fileName":"{{$guid}}",
  "contentType": "image/png"
}

###

@signedUploadUrl = {{generateMedia.response.body.data}}

PUT {{signedUploadUrl}}
Content-Type: image/png

< /Users/duc.nguyen/Downloads/crust-nft/nb-4.png


### NFT Collections

### Create nft collection
POST {{baseUrl}}/api/v1/ntf-collections/
content-type: application/json
Authorization: Bearer {{accessToken}}

{
  "images":[
    {
      "name":"background",
      "id":"d1199842-d735-4b2f-9a78-f4f80e81df4f"
    },
    {
      "name":"head1",
      "id":"8383ffa8-51c8-4b75-9214-fcfe31d7127c"
    },
     {
      "name":"head",
      "id":"giphy2.webp"
    },
     {
      "name":"head",
      "id":"giphy3.gif"
    }
  ],
  "layers":[
     {
      "id": "IDLayer1",
      "name": "Background",
      "imageIds": ["d1199842-d735-4b2f-9a78-f4f80e81df4f", "giphy2.webp"]
    },
    {
      "id": "IDLayer2",
      "name": "Costume",
      "imageIds": ["8383ffa8-51c8-4b75-9214-fcfe31d7127c", "giphy3.gif"]
    }
  ],
  "name":"hello-toro-4444",
  "description":"hello-toro-2",
  "layerOrder":["IDLayer1","IDLayer2"]
}

### Update nft collection
PUT {{baseUrl}}/api/v1/ntf-collections/
content-type: application/json
Authorization: Bearer {{accessToken}}

{
  "id": "7815c682680eadabfa79b906ea4fe8d1",
  "images": [
    {
      "name": "background",
      "id": "d1199842-d735-4b2f-9a78-f4f80e81df4f"
    },
    {
      "name": "head11",
      "id": "8383ffa8-51c8-4b75-9214-fcfe31d7127c"
    },
    {
      "name": "head1",
      "id": "giphy2.webp"
    },
    {
      "name": "head",
      "id": "giphy3.gif"
    }
  ],
  "layers": [
    {
      "id": "IDLayer1",
      "name": "Background",
      "imageIds": [
        "d1199842-d735-4b2f-9a78-f4f80e81df4f",
        "giphy2.webp"
      ]
    },
    {
      "id": "IDLayer2",
      "name": "Costume",
      "imageIds": [
        "8383ffa8-51c8-4b75-9214-fcfe31d7127c",
        "giphy3.gif"
      ]
    }
  ],
  "name": "hello-toro-44fff44",
  "description": "hello-toro-dep trai",
  "layerOrder": [
    "IDLayer1",
    "IDLayer2"
  ]
}

### Get all collections of currentUser
GET {{baseUrl}}/api/v1/ntf-collections/?countOnly=true
content-type: application/json
Authorization: Bearer {{accessToken}}


### Get all collections summary
GET {{baseUrl}}/api/v1/ntf-collections/listing?countOnly=false
content-type: application/json
Authorization: Bearer {{accessToken}}

### Start generate NFT collection
POST {{baseUrl}}/api/v1/ntf-collections/generate-nft-collection
content-type: application/json
Authorization: Bearer {{accessToken}}

{
  "id":"540850332dab49dcafd089b7c8d2044f",
  "composingBatchSize": 2,
  "collectionSize":100
}

### Get generator status
GET {{baseUrl}}/api/v1/ntf-collections/10d021d1c368cfeb9b990e6eeaed3fda
content-type: application/json
Authorization: Bearer {{accessToken}}
