# Correct .env.sample in root folder to use this file, reference: https://marketplace.visualstudio.com/items?itemName=humao.rest-client


@baseUrl = {{$dotenv NFT_GENERATOR_API_ENDPOINT}}
@accessToken = {{$dotenv NFT_GENERATOR_API_ACCESS_TOKEN}}

### Health-check
GET {{baseUrl}}/health


### Media

### Create media upload url
# @name generateMedia
POST {{baseUrl}}/api/v1/medias/
content-type: application/json
Authorization: Bearer {{accessToken}}

{
  "fileName":"{{$guid}}",
  "contentType": "image/png"
}

###

@signedUploadUrl = {{generateMedia.response.body.data}}

PUT {{signedUploadUrl}}
Content-Type: image/png

< /Users/duc.nguyen/Downloads/crust-nft/nb-4.png


### NFT Collections

### Initiate nft collection generator
POST {{baseUrl}}/api/v1/ntf-collections/
content-type: application/json
Authorization: Bearer {{accessToken}}

{
  "medias":[
    {
      "category":"background",
      "mediaId":"4f8d4517-4ea6-4c0b-b9bf-577fa8bf3496"
    },
    {
      "category":"head",
      "mediaId":"809e9b5e-7df9-44a6-a469-07beeca95890"
    }
  ]
}



### Get generator status
GET {{baseUrl}}/api/v1/ntf-collections/589e4386-73db-4336-b4ee-a5ab86273245
content-type: application/json
Authorization: Bearer {{accessToken}}
