steps:
  - name: node:16-bullseye
    entrypoint: npm
    args: ['install']

  - name: node:16-bullseye
    entrypoint: npx
    args: ['nx', 'run-many', '--target=lint', '--all=true']

  - name: node:16-bullseye
    entrypoint: npx
    args: ['nx', 'run-many', '--target=test', '--all=true']

  - name: node:16-bullseye
    entrypoint: npx
    args:
      [
        'nx',
        'run-many',
        '--target=build',
        '--all=true',
        '--configuration=production',
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-f',
        'Dockerfile.prod',
        '-t',
        'gcr.io/$PROJECT_ID/explore-api:$SHORT_SHA',
        '--build-arg=SERVICE_NAME=explore-api',
        '.',
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/explore-api:$SHORT_SHA']

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:376.0.0-slim
    entrypoint: gcloud
    args:
      - datastore
      - indexes
      - create
      - apps/explore-api/index.yaml
      - --quiet
      - --verbosity=info

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:376.0.0-slim
    id: 'deploy-explore-api'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_APP_ENV}-explore-api
      - --image=gcr.io/$PROJECT_ID/explore-api:$SHORT_SHA
      - --platform=managed
      - --ingress=all
      - --allow-unauthenticated
      - --service-account=${_SERVICE_ACCOUNT}
      - --region=${_REGION}
      - --project=$PROJECT_ID
      - --set-env-vars=APP_ENV=${_APP_ENV}

  # - name: gcr.io/google.com/cloudsdktool/cloud-sdk:376.0.0-slim
  #   id: 'deploy-functions-explore-api'
  #   entrypoint: gcloud
  #   args:
  #     - functions
  #     - deploy
  #     - ${_APP_ENV}-explore-api
  #     - --source=./dist/apps/explore-api
  #     - --trigger-http
  #     - --entry-point=api
  #     - --runtime=nodejs16
  #     - --allow-unauthenticated
  #     - --service-account=${_SERVICE_ACCOUNT}
  #     - --region=${_REGION}
  #     - --project=$PROJECT_ID
  #     - --set-env-vars=NODE_ENV=production,APP_ENV=${_APP_ENV}

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-f',
        'Dockerfile.prod',
        '-t',
        'gcr.io/$PROJECT_ID/nft-generator-worker:$SHORT_SHA',
        '--build-arg=SERVICE_NAME=nft-generator-worker',
        '.',
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nft-generator-worker:$SHORT_SHA']

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:376.0.0-slim
    id: 'deploy-nft-generator-worker'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_APP_ENV}-nft-generator-worker
      - --image=gcr.io/$PROJECT_ID/nft-generator-worker:$SHORT_SHA
      - --platform=managed
      - --ingress=all
      - --no-allow-unauthenticated
      - --concurrency=1
      - --cpu=${_NFT_WORKER_CPU}
      - --memory=${_NFT_WORKER_MEMORY}
      - --timeout=60m
      - --max-instances=10
      - --service-account=${_SERVICE_ACCOUNT}
      - --region=${_REGION}
      - --project=$PROJECT_ID
      - --set-env-vars=APP_ENV=${_APP_ENV}

  # - name: gcr.io/google.com/cloudsdktool/cloud-sdk:376.0.0-slim
  #   id: 'deploy-cleanup-worker'
  #   entrypoint: gcloud
  #   args:
  #     - functions
  #     - deploy
  #     - ${_APP_ENV}-cleanup-worker
  #     - --source=./dist/apps/cleanup-worker
  #     - --trigger-http
  #     - --entry-point=api
  #     - --runtime=nodejs16
  #     - --timeout=540s
  #     - --no-allow-unauthenticated
  #     - --service-account=${_SERVICE_ACCOUNT}
  #     - --region=${_REGION}
  #     - --project=$PROJECT_ID
  #     - --set-env-vars=NODE_ENV=production,APP_ENV=${_APP_ENV}

substitutions:
  _APP_ENV: stage
  _REGION: us-east1
  _SERVICE_ACCOUNT: stage-crust-nft-explore@crustnft.iam.gserviceaccount.com
  _NFT_WORKER_MEMORY: 2Gi
  _NFT_WORKER_CPU: '1'

images:
  - 'gcr.io/$PROJECT_ID/explore-api:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/nft-generator-worker:$SHORT_SHA'

timeout: 1800s
